### ISSUE TITLE
The uploaded file is inconsistent with the "README" document

### ISSUE THREAD

**Issue by lilijuanUCAS** [mdpillet/PricklyProspects#1]
I tried to run your code, but I found that the R file you provided was incomplete, and I couldn't find the corresponding explanation from the 'README' document you provided. For example, the R code of getOccurrences.R and subsetOccurrences.R that recorded in the 'README' document cannot be found here. Please complete your documents and document information.

**Comment by mdpillet** [comment]
getOccurrences.R is not provided here as access to the protected BIEN
database containing embargoed species information (including CITES species
such as cacti) needs to be approved. Please see data availability statement
in the article. If you need access to the occurrence data, please email me
directly to discuss.

Thank you,
Michiel
